### ISSUE TITLE
Angular JS could have been used

### ISSUE THREAD

**Issue by karuppiah7890** [dmfarcas/clipboard-manager#1]
You could have used Angular JS to keep up the list of clipboard data and to filter based on search. Easier. And I suppose you show the whole of the data, so Angular should help. Or else not that easy. And I saw that you want to use Mongo DB. Is it advisable ? I mean, Mongo needs a server to run right ? I mean a DB Server. You plan on running a DB server to store this small amount of data ? Why not use some client side storage based methods ?

**Comment by dmfarcas** [comment]
@karuppiah7890 it's using IndexedDB :) It's local

And yes, Angular or React would have been a way better option. 

Might remake the front end at some point, but don't have time yet.


You are free to do a pull request if you want to add Angular :)

**Comment by karuppiah7890** [comment]
Ah, okay. I will think on it. At first I thought I will build it from
scratch. And checked on LevelDB and stuff. I will do it if I have time. Or
else I will do a pull request :) but there are a lot of changes to be done

**Comment by dmfarcas** [comment]
@karuppiah7890 I'm going to redo the front end with React very soon, just so you know. :)

Angular Material might've been a cooler idea but I want some practice with React.
