### ISSUE TITLE
Make it awesome

### ISSUE THREAD

**Issue by akashnimare** [dmfarcas/clipboard-manager#2]
@dmfarcas awesome app. I would love to have a proper installers for this app.
Also you could import some of the features from http://pasteapp.me/. That would be awesome 🚀 .

**Comment by dmfarcas** [comment]
Hello. Thanks, I strongly appreciate it.

I could totally do installers. Just open an issue regarding this.

You should open an issue regarding features that you want to have as well. Won't promise that I'll work on them, will do if I find them interesting enough. :) If you want a feature a lot, you can contribute with a pull request. The code base is quick and dirty, but it's easy to hack on it. I encourage you to do this :)

**Comment by akashnimare** [comment]
@dmfarcas cool. I'll be opening some issues then 😄 .
